import type { ReferenceProject } from "./types";

const now = "2026-01-01T00:00:00.000Z";

export const referencePlaceholders: ReferenceProject[] = [
  {
    id: "placeholder-central-hospital",
    slug: "central-hospital-care-environments",
    projectType: "hospital",
    completedYear: 2025,
    status: "published",
    sortOrder: 10,
    coverImageUrl: "/images/hero-products.png",
    galleryUrls: ["/images/chair1.png"],
    translationStatus: "ready",
    translationError: "",
    translatedAt: now,
    translationSourceUpdatedAt: now,
    updatedAt: now,
    translations: {
      en: {
        locale: "en",
        title: "Creating calmer, more practical care environments for a central hospital",
        summary: "A coordinated furniture project that brought patient comfort, dependable clinical workflows and long-term everyday use into one considered solution.",
        projectTypeLabel: "Hospital",
        location: "Hämeenlinna, Finland",
        unit: "Patient care areas",
        metaTitle: "Central Hospital Care Environments | Woittola References",
        metaDescription: "The story behind a coordinated healthcare furniture project created for modern hospital care environments.",
        contentBlocks: [
          {
            id: "starting-point",
            type: "text",
            heading: "A shared starting point",
            body: "The hospital needed furniture that could support several different care situations without making the environment feel clinical or fragmented. Every space had its own routines, yet patients and professionals needed the same sense of clarity, comfort and confidence throughout the building.\n\nWe began by listening to the people using the rooms every day. Their experience helped define what truly mattered: easy access for care teams, intuitive adjustment, straightforward cleaning and seating that would remain comfortable during longer appointments.",
            imageUrls: [],
            imageAlt: "",
            caption: "",
            imagePosition: "right",
          },
          {
            id: "considered-selection",
            type: "text",
            heading: "Turning daily needs into a considered selection",
            body: "Rather than treating each room as a separate purchase, the project was approached as one connected care environment. Patient chairs, treatment furniture and supporting equipment were evaluated together so that movement, maintenance and visual consistency would work across departments.\n\nThe final selection balances durability with a calm appearance. Controls remain close at hand, surfaces are practical to maintain and each product supports the working positions required by clinical staff.",
            imageUrls: [],
            imageAlt: "",
            caption: "",
            imagePosition: "right",
          },
          {
            id: "lasting-result",
            type: "image-text",
            heading: "A solution designed to last",
            body: "The completed spaces now feel consistent without becoming repetitive. Care teams can move confidently between rooms, while patients encounter furniture that feels approachable and supportive.\n\nMost importantly, the solution is prepared for everyday reality: frequent use, changing patient needs and the high standards expected from a modern healthcare environment.",
            imageUrls: ["/images/chair1.png"],
            imageAlt: "Patient chair selected for the central hospital care environment",
            caption: "A carefully selected patient chair supporting comfort and practical daily care.",
            imagePosition: "right",
          },
        ],
      },
      fi: {
        locale: "fi",
        title: "Rauhallisempia ja toimivampia hoitoympäristöjä keskussairaalaan",
        summary: "Yhtenäinen kalusteprojekti, jossa potilasmukavuus, sujuvat kliiniset työnkulut ja pitkäaikainen päivittäinen käyttö yhdistyvät harkituksi kokonaisuudeksi.",
        projectTypeLabel: "Sairaala",
        location: "Hämeenlinna, Suomi",
        unit: "Potilashoidon tilat",
        metaTitle: "Keskussairaalan hoitoympäristöt | Woittolan referenssit",
        metaDescription: "Tarina moderniin sairaalaympäristöön suunnitellun yhtenäisen terveydenhuollon kalusteprojektin takana.",
        contentBlocks: [
          {
            id: "starting-point",
            type: "text",
            heading: "Yhteinen lähtökohta",
            body: "Sairaala tarvitsi kalusteita, jotka tukevat erilaisia hoitotilanteita ilman, että ympäristö tuntuu kliiniseltä tai hajanaiselta. Jokaisella tilalla oli omat rutiininsa, mutta potilaat ja ammattilaiset tarvitsivat kaikkialla samaa selkeyden, mukavuuden ja luottamuksen tunnetta.\n\nAloitimme kuuntelemalla ihmisiä, jotka käyttävät tiloja päivittäin. Heidän kokemuksensa auttoi tunnistamaan olennaisen: esteettömän työskentelyn, intuitiiviset säädöt, helpon puhdistettavuuden ja istuimet, jotka pysyvät mukavina myös pidempien hoitokäyntien aikana.",
            imageUrls: [],
            imageAlt: "",
            caption: "",
            imagePosition: "right",
          },
          {
            id: "considered-selection",
            type: "text",
            heading: "Arjen tarpeista harkituksi kokonaisuudeksi",
            body: "Yksittäisten huoneiden erillisten hankintojen sijaan projekti nähtiin yhtenäisenä hoitoympäristönä. Potilastuolit, hoitokalusteet ja täydentävät laitteet arvioitiin yhdessä, jotta liikkuminen, ylläpito ja visuaalinen yhtenäisyys toimivat osastolta toiselle.\n\nLopullinen valikoima yhdistää kestävyyden rauhalliseen ilmeeseen. Säädöt ovat helposti ulottuvilla, pinnat käytännöllisiä ylläpitää ja jokainen tuote tukee hoitohenkilökunnan työskentelyasentoja.",
            imageUrls: [],
            imageAlt: "",
            caption: "",
            imagePosition: "right",
          },
          {
            id: "lasting-result",
            type: "image-text",
            heading: "Kestämään suunniteltu ratkaisu",
            body: "Valmiit tilat tuntuvat nyt yhtenäisiltä olematta yksitoikkoisia. Hoitotiimit voivat liikkua huoneiden välillä luontevasti, ja potilaita vastassa ovat helposti lähestyttävät ja tukevat kalusteet.\n\nEnnen kaikkea ratkaisu on valmis arjen todellisuuteen: jatkuvaan käyttöön, muuttuviin potilastarpeisiin ja modernin terveydenhuollon korkeisiin vaatimuksiin.",
            imageUrls: ["/images/chair1.png"],
            imageAlt: "Keskussairaalan hoitoympäristöön valittu potilastuoli",
            caption: "Huolella valittu potilastuoli tukee mukavuutta ja käytännöllistä päivittäistä hoitoa.",
            imagePosition: "right",
          },
        ],
      },
    },
  },
];
